### PR TITLE
Added the scope constant "listPublications"

### PR DESCRIPTION
**Pull request by aki237**
listPublications was not added in the scope constants.

### CODE REVIEW

**Comment by huckphin** [comment]
Hello, @aki237: Thanks for the pull request. Before I accept it, though, may I ask you to sign the CLA for Medium? https://github.com/Medium/opensource/blob/master/sign-cla.md

**Comment by aki237** [comment]
@huckphin I tried signing cla, but gmail said no such user found in the emailing stage

**Comment by huckphin** [comment]
@aki237 - thanks for the following through on this. I am not the best person to respond to the email issue. @nfelsen @dudeche @majelbstoat would have more knowledge and be able to help you in this matter.

**Comment by kylewm** [comment]
Hi @aki237, I think we fixed the issue with the email address, could you try submitting again? Thanks!

**Comment by aki237** [comment]
Thanks, @kylehg, I have sent the email again

**Comment by kylewm** [comment]
Thanks for the catch and the fix!

**Pull request merged**
